### ISSUE TITLE
Issues with the example_project

### ISSUE THREAD

**Issue by jbmouret** [resibots/inria_wbc#111]
- we need to be careful with the `base_path` (we need to set it in the main)
- for the same reason, the `talos.cpp` example segv (files are not found apparently) but it works with explicit command line options: `./talos_graphics -c ../etc/test_controller.yaml -b ../etc/test_behavior.yaml `

**Comment by dalinel** [comment]
The segv was due to the impossibility of using 
```
talos_tracker_controller->torque_sensor_joints()
```
in the example project

Because the example project uses  an almost empty controller class that does not have the ```torque_sensor_joints()``` method

It has been fixed in ```devel```
