### ISSUE TITLE
versions - branches

### ISSUE THREAD

**Issue by M-Amin-Ali** [resibots/inria_wbc#112]
Hi,
Which versions/branches (dart, robot_dart, cxx, etc ...) do you recommend for an Ubuntu 18.04 (manual installation)?
Thanks a lot

**Comment by dalinel** [comment]
Hi
You can check the docker files of [https://gitlab.inria.fr/locolearn/public/docker_inria_wbc](https://gitlab.inria.fr/locolearn/public/docker_inria_wbc)

I have checked and both ```master``` and ```2021.01``` manages to install ```inria_wbc```


For example 
You can see [here](https://gitlab.inria.fr/locolearn/public/docker_inria_wbc/-/blob/master/pinocchio_tsid/Dockerfile#L51) that we uses ```tsid ``` ```devel``` branch

and [here](https://gitlab.inria.fr/locolearn/public/docker_inria_wbc/-/blob/master/inria_wbc/Dockerfile#L20) that we uses ```inria_wbc``` ```devel``` branch
