### ISSUE TITLE
Do not add robot_dart as a dependency of the library

### ISSUE THREAD

**Issue by jbmouret** [resibots/inria_wbc#21]
Even if robot_dart (and Magnum) are detected, we should not link to it in inria_wbc (only in the examples) to avoid link issues for the users of the library.

**Comment by jbmouret** [comment]
@ivanbergonzani didn't you address this in #28 ?

**Comment by ivanbergonzani** [comment]
Yes, the dependency has been removed

**Comment by jbmouret** [comment]
Fixed in #28
