### ISSUE TITLE
Improve reference tracking

### ISSUE THREAD

**Issue by ibergonzani** [resibots/inria_wbc#68]
for now, we do not give acceleration references and velocity references in the behaviors

REQUIRED
Add velocity, acceleration references and  compare the tracking performance with three cases :
 - position ref like it is now
- change the task in TSID (take a new one) that does not have any reference for velocity and acceleration (let the optimizer decide withing the bounds)
- specify acceleration and velocity (which we can compute when we generate the trajectory)

**Comment by dalinel** [comment]
This has been merged already
